version: "3.7"

networks:
  skynet:

volumes: 
  database:

services:
  ormdata:
    container_name: ormdata
    image: bookmarks.azurecr.io/bookmark-ormdata
    environment: 
      ACCEPT_EULA: "y"
      SA_PASSWORD: "Password12345"
    expose: 
      - 1433
    ports: 
      - 1433:1433
    networks: 
      - skynet
    volumes: 
      - database:/var/opt/mssql/data
  restapi:
    container_name: restapi
    depends_on: 
      - ormdata
    image: bookmarks.azurecr.io/bookmark-restapi
    environment: 
      RestApiUrl: "http://restapi"
    expose:
      - 5000
    ports:
      - 5000:80
    networks:
      - skynet
    links: 
      - ormdata
    restart: always
  client:
    container_name: client
    depends_on: 
      - ormdata
      - restapi
    image: bookmarks.azurecr.io/bookmark-client
    environment: 
      RestApiUrl: "http://restapi"
    ports:
      - 8000:80
    networks:
      - skynet
    links:
    - restapi
