// <auto-generated />
using System;
using BookMark.RestApi.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookMark.RestApi.Migrations
{
    [DbContext(typeof(BookMarkDbContext))]
    [Migration("20200407090818_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookMark.RestApi.Models.Appointment", b =>
                {
                    b.Property<long>("AppointmentID")
                        .HasColumnType("bigint");

                    b.Property<long>("AppointmentGroupID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("AppointmentID");

                    b.HasIndex("AppointmentGroupID");

                    b.HasIndex("UserID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("BookMark.RestApi.Models.AppointmentGroup", b =>
                {
                    b.Property<long>("AppointmentGroupID")
                        .HasColumnType("bigint");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrganizationID")
                        .HasColumnType("bigint");

                    b.HasKey("AppointmentGroupID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("AppointmentGroups");
                });

            modelBuilder.Entity("BookMark.RestApi.Models.Event", b =>
                {
                    b.Property<long>("EventID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrganizationID")
                        .HasColumnType("bigint");

                    b.HasKey("EventID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("BookMark.RestApi.Models.Organization", b =>
                {
                    b.Property<long>("OrganizationID")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationID");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            OrganizationID = 1L,
                            Email = "revature@mail.com",
                            Name = "revature",
                            Password = "$2a$11$DR63GSNJooZlE3EHIe40OOyvSqb2EnSRgnMUVVp9TnOqITUbBY7VG"
                        });
                });

            modelBuilder.Entity("BookMark.RestApi.Models.User", b =>
                {
                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1L,
                            Email = "tylercadena@alum.calarts.edu",
                            Name = "synaodev",
                            Password = "$2a$11$BZFLFLGM.jm213yXKI6NT.Bv3m4ti1VkaSiG/5RKR0JFXVpGUE/Um"
                        },
                        new
                        {
                            UserID = 2L,
                            Email = "adrienne-sparkman@gmail.com",
                            Name = "adrienne",
                            Password = "$2a$11$FdMGlzdyHiKCjeoVO/4ZnesWyvOfHgktffZSwHx4I//eZLNWfXhH."
                        });
                });

            modelBuilder.Entity("BookMark.RestApi.Models.UserEvent", b =>
                {
                    b.Property<long>("UserEventID")
                        .HasColumnType("bigint");

                    b.Property<long>("EventID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("UserEventID");

                    b.ToTable("UserEvents");
                });

            modelBuilder.Entity("BookMark.RestApi.Models.Appointment", b =>
                {
                    b.HasOne("BookMark.RestApi.Models.AppointmentGroup", "AppointmentGroup")
                        .WithMany("Appointments")
                        .HasForeignKey("AppointmentGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookMark.RestApi.Models.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookMark.RestApi.Models.AppointmentGroup", b =>
                {
                    b.HasOne("BookMark.RestApi.Models.Organization", "Organization")
                        .WithMany("AppointmentGroups")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookMark.RestApi.Models.Event", b =>
                {
                    b.HasOne("BookMark.RestApi.Models.Organization", "Organization")
                        .WithMany("Events")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookMark.RestApi.Models.UserEvent", b =>
                {
                    b.HasOne("BookMark.RestApi.Models.Event", "Event")
                        .WithMany("UserEvents")
                        .HasForeignKey("UserEventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookMark.RestApi.Models.User", "User")
                        .WithMany("UserEvents")
                        .HasForeignKey("UserEventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
